### ISSUE TITLE
Unknown option connect

### ISSUE THREAD

**Issue by Blkzer0** [yeti-platform/yeti#141]
When i try running yeti as webui via ./yeti.py webserver command, im greeted with the following error:

 $ ./yeti.py webserver
Traceback (most recent call last):
  File "./yeti.py", line 7, in <module>
    from core.web import webapp
  File "/home/username/yeti/core/__init__.py", line 16, in <module>
    connect=False
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/connection.py", line 257, in connect
    return get_connection(alias)
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/connection.py", line 215, in get_connection
    'Cannot connect to database %s :\n%s' % (alias, e))
mongoengine.connection.MongoEngineConnectionError: Cannot connect to database default :
Unknown option connect

everything installed correctly and i didnt run into any errors when installing. I am testing this on Ubuntu 17.04 64bit

**Comment by tomchop** [comment]
It looks like mongo is having some trouble. Can paste the output of `$ mongod -v`? Also, make sure it's running and listening on 127.0.0.1:27017

**Comment by Blkzer0** [comment]
2017-09-27T10:53:52.641-0400 I CONTROL  [initandlisten] MongoDB starting : pid=5330 port=27017 dbpath=/data/db 64-bit host=Username
2017-09-27T10:53:52.641-0400 I CONTROL  [initandlisten] db version v3.2.11
2017-09-27T10:53:52.641-0400 I CONTROL  [initandlisten] git version: 009580ad490190ba33d1c6253ebd8d91808923e4
2017-09-27T10:53:52.641-0400 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
2017-09-27T10:53:52.641-0400 I CONTROL  [initandlisten] allocator: tcmalloc
2017-09-27T10:53:52.641-0400 I CONTROL  [initandlisten] modules: none
2017-09-27T10:53:52.641-0400 I CONTROL  [initandlisten] build environment:
2017-09-27T10:53:52.641-0400 I CONTROL  [initandlisten]     distarch: x86_64
2017-09-27T10:53:52.641-0400 I CONTROL  [initandlisten]     target_arch: x86_64
2017-09-27T10:53:52.641-0400 I CONTROL  [initandlisten] options: { systemLog: { verbosity: 1 } }
2017-09-27T10:53:52.641-0400 D NETWORK  [initandlisten] fd limit hard:4096 soft:1024 max conn: 819
2017-09-27T10:53:52.676-0400 E NETWORK  [initandlisten] listen(): bind() failed errno:98 Address already in use for socket: 0.0.0.0:27017
2017-09-27T10:53:52.676-0400 E NETWORK  [initandlisten]   addr already in use
2017-09-27T10:53:52.676-0400 E STORAGE  [initandlisten] Failed to set up sockets during startup.
2017-09-27T10:53:52.676-0400 I CONTROL  [initandlisten] dbexit:  rc: 48

It seems that the address is already in use, i thought maybe its because of netdata but the address for netdata is 127.0.0.1:19999.

**Comment by tomchop** [comment]
Maybe mongo is already running then? Can you double-check what's running on port 27017?

**Comment by Blkzer0** [comment]
netstat shows me:
tcp        0      0 localhost:27017         localhost:58036         ESTABLISHED
tcp        0      0 localhost:58036         localhost:27017         ESTABLISHED

I did verify that mongodb is running. i cant get anymore info on what service is using 58036.

**Comment by tomchop** [comment]
OK. Can you tell me what version of mongoengine you're running? try running `$ pip freeze | grep mongoengine` from your virtualenv.

**Comment by Blkzer0** [comment]
flask-mongoengine==0.9.3
mongoengine==0.13.0

**Comment by tomchop** [comment]
This is what I have:

```
$ pip freeze | grep -i mongo
flask-mongoengine==0.9.2
mongoengine==0.14.3
mongomock==3.7.0
pymongo==3.5.1
```

Try upgrading these packages and see if that fixes it.
