### ISSUE TITLE
Mongo db error

### ISSUE THREAD

**Issue by DigiAngel** [yeti-platform/yeti#149]
### Description
Mongo db error

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | commit d4342459b49cd8b5b3c9c5b211f2ee97382e65a8
| OS version       | Debian stretch
| Browser          | Chrome 57.0.2987.133 (64-bit)

### Steps to Reproduce
1. Start any of the celery processes

#### Expected behavior
To update feed info

#### Actual behavior
Error:
~~~
mongoengine.errors.NotUniqueError: Tried to save duplicate unique keys (E11000 duplicate key error collection: yeti.one_shot_entry index: name_1 dup key: { : "Whois" })
~~~

**Comment by tomchop** [comment]
I just did a Whois query through the investigation interface and everything worked out for me. Can you please detail the steps you took to see this? Does it happy when the celery process is launched? Or when a task is sent?

Also, given the error message it may mean that you have more than one one_shot_entry named "Whois". Can you try dumping that collection for me?

**Comment by DigiAngel** [comment]
Well hey Tom!  So when I attempted to start the celery process:
~~~
celery -A core.config.celeryctl.celery_app worker --loglevel=ERROR -Q feeds -n feeds -Ofair -c 2 --purge
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/home/jlay/.local/lib/python2.7/site-packages/celery/__main__.py", line 14, in main
    _main()
  File "/home/jlay/.local/lib/python2.7/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/home/jlay/.local/lib/python2.7/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/jlay/.local/lib/python2.7/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/jlay/.local/lib/python2.7/site-packages/celery/bin/celery.py", line 480, in handle_argv
    return self.execute(command, argv)
  File "/home/jlay/.local/lib/python2.7/site-packages/celery/bin/celery.py", line 412, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/home/jlay/.local/lib/python2.7/site-packages/celery/bin/worker.py", line 221, in run_from_argv
    return self(*args, **options)
  File "/home/jlay/.local/lib/python2.7/site-packages/celery/bin/base.py", line 244, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/jlay/.local/lib/python2.7/site-packages/celery/bin/worker.py", line 255, in run
    **kwargs)
  File "/home/jlay/.local/lib/python2.7/site-packages/celery/worker/worker.py", line 94, in __init__
    self.app.loader.init_worker()
  File "/home/jlay/.local/lib/python2.7/site-packages/celery/loaders/base.py", line 116, in init_worker
    self.import_default_modules()
  File "/home/jlay/.local/lib/python2.7/site-packages/celery/loaders/base.py", line 111, in import_default_modules
    return [self.import_task_module(m) for m in self.default_modules]
  File "/home/jlay/.local/lib/python2.7/site-packages/celery/loaders/base.py", line 97, in import_task_module
    return self.import_from_cwd(module)
  File "/home/jlay/.local/lib/python2.7/site-packages/celery/loaders/base.py", line 106, in import_from_cwd
    package=package,
  File "/home/jlay/.local/lib/python2.7/site-packages/celery/utils/imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "/home/jlay/.local/lib/python2.7/site-packages/celery/loaders/base.py", line 100, in import_module
    return importlib.import_module(module, package=package)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/yeti/core/config/celeryimports.py", line 4, in <module>
    loaded_modules = get_plugins()
  File "/opt/yeti/core/yeti_plugins.py", line 25, in get_plugins
    entry.save()
  File "/home/jlay/.local/lib/python2.7/site-packages/mongoengine/document.py", line 364, in save
    raise NotUniqueError(message % six.text_type(err))
mongoengine.errors.NotUniqueError: Tried to save duplicate unique keys (E11000 duplicate key error collection: yeti.one_shot_entry index: name_1 dup key: { : "Whois" })
~~~

It wasn't mission critical so I nuked the db and everything is working fine.  Thank you!

**Comment by ag100** [comment]
I've seen this as well, especially after upgrades.  I just recreated it on a test instance.  GUI returns a 500 - Internal server error on all pages when it occurs.  Details are below, 

# service yeti_oneshot status
....
May 24 14:17:16 yeti celery[255]:     parse_write_concern_error=parse_write_concern_error)
May 24 14:17:16 yeti celery[255]:   File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 138, in _check_command_response
May 24 14:17:16 yeti celery[255]:     raise DuplicateKeyError(errmsg, code, response)
May 24 14:17:16 yeti celery[255]: DuplicateKeyError: E11000 duplicate key error collection: yeti.one_shot_entry index: name_1 dup key: { : "Passive DNS" }

In Mongo:

> db.one_shot_entry.find({"name": "Passive DNS"})
> use yeti
switched to db yeti
> db.one_shot_entry.find({"name": "Passive DNS"})
{ "_id" : ObjectId("5ac228734e563b15fa6ba122"), "_cls" : "OneShotEntry.OneShotAnalytics.DNSDBPassiveDns", "name" : "Passive DNS", "enabled" : true, "description" : "Perform passive DNS lookups on domain names.", "group" : "DNSDB" }
{ "_id" : ObjectId("5ac228754e563b15fa6ba12e"), "_cls" : "OneShotEntry.OneShotAnalytics.PassiveTotalPassiveDNS", "name" : "Passive DNS", "enabled" : true, "description" : "Perform passive DNS (reverse) lookups on domain names or IP addresses.", "group" : "PassiveTotal" }


The name for the Passive Total PDNS entry appears to include "PassiveTotal" so not 100% sure why it's not reflecting the name properly, but will look into it.

**Comment by ag100** [comment]
The issues I've seen related to this appear to occur when items are modified between versions.  For example, in the above, the name was changed from "Passive DNS" to "PassiveTotal Passive DNS".  After running the git pull, multiple entries then exist for the same _cls.  I've started removing mongo entries for items that have changed prior to upgrading, and everything has worked pretty well since.

**Comment by tomchop** [comment]
I can write a migration that clears the feed data and puts it back in a consistent state. Would that help?

**Comment by ag100** [comment]
Good thought, and probably, yeah. It's not as much an issue for me now that I know what was happening, but the first time I upgraded the code and ran into it, it drove me crazy for a little while.  IMO, as long as it's noted somewhere and folks know what to do when upgrading, that's probably good enough.  I can take a stab at scripting it as well if you'd like.

**Comment by tomchop** [comment]
A script would be cool! But if you're headed down that road, you might want to check out migrations, they were exactly made for that and they're pretty easy to do. Example: 39ac45deb91df8389c5f0f3ec6fa23437580f224

**Comment by ag100** [comment]
Thanks Tom - I'll take a look.

Aaron
