### ISSUE TITLE
error when redis database ≠ 0

### ISSUE THREAD

**Issue by truckydev** [yeti-platform/yeti#166]
### Description
when I put "database = 28", for example,  for redis configuration  in "yeti. conf" I then get an error when I try to update my feed misp.

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | last
| OS version       | debian9

### Steps to Reproduce
1. change redis database in yeti.conf
2. ./yeti.py webserver
3. go to http://127.0.0.1:5000/dataflows
4. try to update MispFeed

#### Expected behavior
No error ^^

#### Actual behavior
```bash
./yeti.py webserver
[+] Database version is synced with code.
[+] Yeti started. Point browser to http://localhost:5000/
[2017-11-13 19:05:32,375] ERROR in app: Exception on /api/feed/5a09d92eed59f0646d707530/refresh [POST]
Traceback (most recent call last):
  File ".local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File ".local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File ".local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File ".local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File ".local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_classy.py", line 200, in proxy
    response = view(**request.view_args)
  File "yeti/core/web/helpers.py", line 32, in inner
    return f(*args, **kwargs)
  File "yeti/core/web/api/feeds.py", line 25, in refresh
    feed.update_feed.delay(id)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 412, in delay
    return self.apply_async(args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 535, in apply_async
    **options
  File "/usr/local/lib/python2.7/dist-packages/celery/app/base.py", line 737, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/amqp.py", line 558, in send_task_message
    **properties
  File "/usr/local/lib/python2.7/dist-packages/kombu/messaging.py", line 181, in publish
    exchange_name, declare,
  File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 527, in _ensured
    errback and errback(exc, 0)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 419, in _reraise_as_library_errors
    sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 414, in _reraise_as_library_errors
    yield
  File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 515, in _ensured
    reraise_as_library_errors=False,
  File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 405, in ensure_connection
    callback)
  File "/usr/local/lib/python2.7/dist-packages/kombu/utils/functional.py", line 333, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 261, in connect
    return self.connection
  File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 802, in connection
    self._connection = self._establish_connection()
  File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 757, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/virtual/base.py", line 941, in establish_connection
    self._avail_channels.append(self.create_channel(self))
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/virtual/base.py", line 923, in create_channel
    channel = self.Channel(connection)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 501, in __init__
    self.client.ping()
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 777, in ping
    return self.execute_command('PING')
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 493, in connect
    self.on_connect()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 567, in on_connect
    if nativestr(self.read_response()) != 'OK':
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 629, in read_response
    raise response
OperationalError: invalid DB index
```

**Comment by tomchop** [comment]
[This](https://stackoverflow.com/questions/14287075/rediscommanderror-err-invalid-db-index-when-running-rspec) seems to point out to a tweak in redis' configuration file. Can you double-check you've launched redis with at least 29 databases available?

**Comment by truckydev** [comment]
Ok, I close. 
Redis as only 16 database lol :)

maybe add this check later ^^
