### ISSUE TITLE
Upgtra

### ISSUE THREAD

**Issue by ag100** [yeti-platform/yeti#218]
I've upgraded a couple of test instances (git pull, yeti.py syncdb), and  am seeing errors on both instances when viewing the details of an entity.  For example, clicking on "Entities --> Campaigns", then selecting a campaign, no bound entities or observables show up in the detail tabs, and syslog is reporting multiple errors:

Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]: [Neighbors] Filter: {}
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]: message repeated 5 times: [ [Neighbors] Filter: {}]
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]: [2018-01-23 12:36:52,804] ERROR in app: Exception on /api/neighbors/tuples/entity/5a5fd9e637ea9d395f93ead9/actor [POST]
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]: Traceback (most recent call last):
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:     response = self.full_dispatch_request()
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:     rv = self.handle_user_exception(e)
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:     reraise(exc_type, exc_value, tb)
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:     rv = self.dispatch_request()
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:     return self.view_functions[rule.endpoint](**req.view_args)
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:   File "/usr/local/lib/python2.7/dist-packages/flask_classy.py", line 200, in proxy
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:     response = view(**request.view_args)
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:   File "./core/web/helpers.py", line 37, in inner
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:     return f(*args, **kwargs)
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:   File "./core/web/api/neighbors.py", line 68, in tuples
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:     filter_class, fltr, regex, ignorecase, page, rng)
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:   File "./core/database.py", line 445, in neighbors_advanced
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:     "out", klass, result_filters, page, rng)
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:   File "./core/database.py", line 422, in _neighbors_aggregation
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:     results = list(Link.objects.aggregate(*pipeline))
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:   File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py", line 1185, in aggregate
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:     return self._collection.aggregate(pipeline, cursor={}, **kwargs)
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:   File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1922, in aggregate
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:     collation=collation)
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:   File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 232, in _command
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:     collation=collation)
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:   File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 477, in command
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:     collation=collation)
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:   File "/usr/local/lib/python2.7/dist-packages/pymongo/network.py", line 116, in command
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:     parse_write_concern_error=parse_write_concern_error)
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:   File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 210, in _check_command_response
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]:     raise OperationFailure(msg % errmsg, code, response)
Jan 23 12:36:52 ip-10-44-103-163 uwsgi[1288]: OperationFailure: exception: invalid operator '$arrayElemAt'

I am going to dig into this over the next few days, but wanted to open this in case others are seeing it as well.

**Comment by tomchop** [comment]
Hm interesting. What version of mongodb are you running? What version of pymongo is yeti running with?

**Comment by ag100** [comment]
Thanks Tom - Both systems are using:

Mongo: 2.6.10
pymongo==3.5.1

I'll try to do some digging as well a bit later.

**Comment by tomchop** [comment]
Hm I think you're running a pretty old version of mongo :) `arrayElementAt` was introduced in 3.2: https://docs.mongodb.com/manual/reference/operator/aggregation/arrayElemAt/

**Comment by ag100** [comment]
Ok, thanks *duh*  :) That was the latest version that came down with Ubuntu 16.04.3.  I will upgrade manually and provide an update.

**Comment by ag100** [comment]
That worked, sorry about that..   For anyone else who runs into this, instructions on how to upgrade Mongo on Ubuntu 16.04  are below.

$ sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6

$ echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list

$ sudo apt-get update

$ sudo apt-get install -y mongodb-org

$ sudo systemctl unmask mongodb

**Comment by tomchop** [comment]
Thanks a bunch for the tips! Closing this out.
