### ISSUE TITLE
Support for Sharded Clusters

### ISSUE THREAD

**Issue by scrublullz** [yeti-platform/yeti#219]
### Description
After migrating data to a sharded MongoDB cluster, observables are failing to update due to missing shard key. 

### Environment
```
commit 2df99e7f1fc7ec640f10463388150c471db6b3fc
Ubuntu 16.04 LTS
Mongo 4.6.2
```

### Steps to Reproduce
`sh.shardCollection( "yeti.observable", { "_id" : "hashed" } )`

### Supporting Detail
```
Jan 23 17:36:09 ServerName celery[2413]: [2018-01-23 17:36:09,997: ERROR/PoolWorker-6] UNKNOWN EXCEPTION: Update failed (Query for sharded findAndModify must contain the shard key)
Jan 23 17:36:10 ServerName celery[2413]: [2018-01-23 17:36:10,002: ERROR/PoolWorker-5] Traceback (most recent call last):
Jan 23 17:36:10 ServerName celery[2413]:   File "/datapool/yeti/core/feed.py", line 42, in update_feed
Jan 23 17:36:10 ServerName celery[2413]:     f.update()
Jan 23 17:36:10 ServerName celery[2413]:   File "/datapool/yeti/plugins/feeds/public/vxvault_url.py", line 24, in update
Jan 23 17:36:10 ServerName celery[2413]:     self.analyze(line)
Jan 23 17:36:10 ServerName celery[2413]:   File "/datapool/yeti/plugins/feeds/public/vxvault_url.py", line 38, in analyze
Jan 23 17:36:10 ServerName celery[2413]:     url = Url.get_or_create(value=data.rstrip())
Jan 23 17:36:10 ServerName celery[2413]:   File "/datapool/yeti/core/database.py", line 81, in get_or_create
Jan 23 17:36:10 ServerName celery[2413]:     return obj.save()
Jan 23 17:36:10 ServerName celery[2413]:   File "/usr/local/lib/python2.7/dist-packages/mongoengine/document.py", line 423, in save
Jan 23 17:36:10 ServerName celery[2413]:     created=created, **signal_kwargs)
Jan 23 17:36:10 ServerName celery[2413]:   File "/usr/local/lib/python2.7/dist-packages/blinker/base.py", line 267, in send
Jan 23 17:36:10 ServerName celery[2413]:     for receiver in self.receivers_for(sender)]
Jan 23 17:36:10 ServerName celery[2413]:   File "/datapool/yeti/core/analytics.py", line 64, in post_save
Jan 23 17:36:10 ServerName celery[2413]:     analytics.each(document)
Jan 23 17:36:10 ServerName celery[2413]:   File "/datapool/yeti/plugins/analytics/public/process_url.py", line 36, in each
Jan 23 17:36:10 ServerName celery[2413]:     h.add_source("analytics")
Jan 23 17:36:10 ServerName celery[2413]:   File "/datapool/yeti/core/observables/observable.py", line 269, in add_source
Jan 23 17:36:10 ServerName celery[2413]:     return self.modify(add_to_set__sources=source)
Jan 23 17:36:10 ServerName celery[2413]:   File "/usr/local/lib/python2.7/dist-packages/mongoengine/document.py", line 250, in modify
Jan 23 17:36:10 ServerName celery[2413]:     updated = self._qs(**query).modify(new=True, **update)
Jan 23 17:36:10 ServerName celery[2413]:   File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py", line 627, in modify
Jan 23 17:36:10 ServerName celery[2413]:     raise OperationError(u'Update failed (%s)' % err)
Jan 23 17:36:10 ServerName celery[2413]: OperationError: Update failed (Query for sharded findAndModify must contain the shard key)
```

Information from Mongo:
https://docs.mongodb.com/manual/reference/method/db.collection.findAndModify/#behavior

#### Sharded Collections
When using findAndModify in a sharded environment, the query must contain the shard key for all operations against the sharded cluster for the sharded collections.

findAndModify operations issued against mongos instances for non-sharded collections function normally.

**Comment by tomchop** [comment]
As discussed offline, sharding comes with it's own set of problems. I can't recall, was this specific issue solved?

**Comment by scrublullz** [comment]
We had to install a new, unreleased version of PyMongo in order to kill off the above errors.

In Yeti, we had to roll back to a version before aggregation was added as it would cause errors when doing entity lookup. 

You discussed adding a configuration option in future releases that account for the aggregation. Basically, if your mongo setup is sharded, do not use the new aggregation features.

**Comment by tomchop** [comment]
Closing this since I don't think you need this anymore and implementing it would result in performance loss in most setups.
