### ISSUE TITLE
yeti.py webserver throws error

### ISSUE THREAD

**Issue by antwanvanderstap** [yeti-platform/yeti#241]
### Description
- Clean install of Ubuntu 16.04; Yeti works fine
- After installation of pyeti:
Traceback (most recent call last):
  File "/opt/yeti/yeti.py", line 7, in <module>
    from core.web import webapp
  File "/opt/yeti/core/__init__.py", line 4, in <module>
    from core.exports import Export
  File "/opt/yeti/core/exports/__init__.py", line 1, in <module>
    from core.exports.export import ExportTemplate
  File "/opt/yeti/core/exports/export.py", line 16, in <module>
    from core.config.celeryctl import celery_app
  File "/opt/yeti/core/config/celeryctl.py", line 3, in <module>
    from celery import Celery
  File "/usr/local/lib/python2.7/dist-packages/celery/local.py", line 509, in __getattr__
    module = __import__(self._object_origins[name], None, None, [name])
  File "/usr/local/lib/python2.7/dist-packages/celery/app/__init__.py", line 5, in <module>
    from celery import _state
  File "/usr/local/lib/python2.7/dist-packages/celery/_state.py", line 15, in <module>
    from celery.utils.threads import LocalStack
  File "/usr/local/lib/python2.7/dist-packages/celery/utils/__init__.py", line 10, in <module>
    from .nodenames import worker_direct, nodename, nodesplit
  File "/usr/local/lib/python2.7/dist-packages/celery/utils/nodenames.py", line 7, in <module>
    from kombu.entity import Exchange, Queue
  File "/usr/local/lib/python2.7/dist-packages/kombu/entity.py", line 6, in <module>
    from .abstract import MaybeChannelBound, Object
  File "/usr/local/lib/python2.7/dist-packages/kombu/abstract.py", line 6, in <module>
    from .connection import maybe_channel
  File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 20, in <module>
    from .log import get_logger
  File "/usr/local/lib/python2.7/dist-packages/kombu/log.py", line 9, in <module>
    from logging.handlers import WatchedFileHandler
ImportError: cannot import name WatchedFileHandler

Anyone seen this before?
Tried to look at the ../kumbo/log.py file but not smart enough to figure this one out

**Comment by antwanvanderstap** [comment]
Going to reproduce today and keep you updated!

**Comment by antwanvanderstap** [comment]
Reimaged my Ubuntu server and used the Quick install to get Yeti up and running. Did a pip install for pyeti and things seem to work now.
I did noticed that the quick install needs a little tweak after if Apache2 is running on a server - bu that was just a matter of turning off and remove Apache2 in my case.
Thanks for your response!
