### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'name' in file core/entities/malware.py

### ISSUE THREAD

**Issue by Honesty1997** [yeti-platform/yeti#272]
I got the error message below when I searched a new observarable which should match a certain indicator. 
```
ERROR:app:Exception on /observable/ [POST]
Traceback (most recent call last):
  File "/Users/phil/homebrew/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/phil/homebrew/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/phil/homebrew/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/phil/homebrew/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/phil/homebrew/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/phil/homebrew/lib/python2.7/site-packages/flask_classy.py", line 200, in proxy
    response = view(**request.view_args)
  File "/Users/phil/Desktop/Projects/yeti/yeti/core/web/helpers.py", line 37, in inner
    return f(*args, **kwargs)
  File "/Users/phil/Desktop/Projects/yeti/yeti/core/web/frontend/observables.py", line 111, in index
    data = match_observables(obs.keys())
  File "/Users/phil/Desktop/Projects/yeti/yeti/core/analysis.py", line 147, in match_observables
    for tag in node.generate_tags():
  File "/Users/phil/Desktop/Projects/yeti/yeti/core/entities/malware.py", line 43, in generate_tags
    return [self.name.lower(), self.family.name.lower()]
AttributeError: 'NoneType' object has no attribute 'name'
```
I found the problem is that the indicator links to an entity which has no family.

So in ```yeti/core/entities/malware.py``` file,
```
    def generate_tags(self):
        return [self.name.lower(), self.family.name.lower()]
```
Should the class method check the family is none or not before it returns?
Maybe something like
```
   def generate_tags(self):
        tags = [self.name.lower()]
        if self.family is not None:
            tags.append(self.family.name.lower())
        return tags

**Comment by tomchop** [comment]
Yeah that would be a good patch, thanks for reporting the bug and finding a fix!
