### ISSUE TITLE
pymongo.errors.ServerSelectionTimeoutError: 127.0.0.1:27017: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by ironbits** [yeti-platform/yeti#285]
Before opening an issue, please make do a quick search through the current issues
and the mailing list (https://groups.google.com/forum/#!forum/yeti-users) to see
if it hasn't been answered already.

### Description
Traceback (most recent call last):
  File "./yeti.py", line 53, in <module>
    main()
  File "./yeti.py", line 49, in main
    COMMANDS[command](args)
  File "./yeti.py", line 20, in webserver
    syncdb()
  File "./yeti.py", line 28, in syncdb
    Internals.syncdb()
  File "/opt/yeti/core/internals/internals.py", line 18, in syncdb
    current_version = klass.get_internals().db_version
  File "/opt/yeti/core/internals/internals.py", line 29, in get_internals
    klass.__internal = Internals.get_or_create(name="default")
  File "/opt/yeti/core/database.py", line 89, in get_or_create
    r = cls.objects(**select_dict).modify(upsert=True, **update_dict)
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/manager.py", line 37, in __get__
    queryset = queryset_class(owner, owner._get_collection())
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/document.py", line 201, in _get_collection
    db.client.is_primary:
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 857, in is_primary
    return self._server_property('is_writable')
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 689, in _server_property
    writable_server_selector)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 224, in select_server
    address))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 183, in select_servers
    selector, server_timeout, address)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 199, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: 127.0.0.1:27017: [Errno 111] Connection refused

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log | head -n1` to find out
| OS version       | Ubuntu 16.04
| Browser          | Chrome 56.0.2924.87

### Steps to Reproduce

$ curl https://raw.githubusercontent.com/yeti-platform/yeti/master/extras/ubuntu_bootstrap.sh | sudo /bin/bash

#### Expected behavior
Traceback (most recent call last):
  File "./yeti.py", line 53, in <module>
    main()
  File "./yeti.py", line 49, in main
    COMMANDS[command](args)
  File "./yeti.py", line 20, in webserver
    syncdb()
  File "./yeti.py", line 28, in syncdb
    Internals.syncdb()
  File "/opt/yeti/core/internals/internals.py", line 18, in syncdb
    current_version = klass.get_internals().db_version
  File "/opt/yeti/core/internals/internals.py", line 29, in get_internals
    klass.__internal = Internals.get_or_create(name="default")
  File "/opt/yeti/core/database.py", line 89, in get_or_create
    r = cls.objects(**select_dict).modify(upsert=True, **update_dict)
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/manager.py", line 37, in __get__
    queryset = queryset_class(owner, owner._get_collection())
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/document.py", line 201, in _get_collection
    db.client.is_primary:
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 857, in is_primary
    return self._server_property('is_writable')
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 689, in _server_property
    writable_server_selector)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 224, in select_server
    address))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 183, in select_servers
    selector, server_timeout, address)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 199, in _select_servers_loop
    self._error_message(selector))

**Comment by ironbits** [comment]
![screenshot from 2018-08-21 07-43-19](https://user-images.githubusercontent.com/6081236/44397315-53e23f80-a516-11e8-84aa-efa07dac82ca.png)

**Comment by tomchop** [comment]
Yeti can't connect to the mongodb server because it's apparently not running. Please make sure it's running and try again.

That being said, the bootstrap scripts are supposed to start the mongo server automatically. Can you please paste the full output of the `curl | bash` command?

`$ curl https://raw.githubusercontent.com/yeti-platform/yeti/master/extras/ubuntu_bootstrap.sh | sudo /bin/bash`

**Comment by redNixon** [comment]
I've been attempting to get Yeti to run the for past few days, this is one of the recurring issues that I am seeing when trying to use docker; can't figure out who is telling it to use 127.0.0.1 instead of the docker link, every 40-60 seconds it will throw this error and deauth the logged in users... then start working correctly again(mongo container is up the whole time).

**Comment by tomchop** [comment]
Hm, can you open a new issue so we can track this? It seems to be a bit different from this one.

A few questions off the top of my head:

* How exactly are you running Yeti through docker? I assume docker-compose?
* What do you mean by "docker link"? The link attribute in the docker-compose file?
* According to the [Dockerfile](https://github.com/yeti-platform/yeti/blob/master/extras/docker/Dockerfile#L46), 127.0.0.1 is being replaced by `mongodb` and `redis` depending on which line of the config file it's editing.

To further troubleshoot, I would recommend breaking into that container and examining the config file, and whether the `mongodb` and `redis` hosts are reachable from that container.
