### ISSUE TITLE
Running Yeti completely from within virtualenv

### ISSUE THREAD

**Issue by smclinden** [yeti-platform/yeti#291]
I'm trying to understand how to run a product Yeti instance from virtualenv. I have one box on which I am placing a number of services and using virtualenv to control the Python instance. But when I try to run the workers from the venv, I get:

ImportError: No module named core.config.celeryctl when I try to start the workers.

Help would be appreciated.

**Comment by sebdraven** [comment]
If you use services , you have to install yeti on the server. If you want to use the virtualenv you can launch celery on a screen.

**Comment by smclinden** [comment]
The problem that I have with the requirements is that it appears that on Ubuntu 18.04 pdfminer can only be built with Python 2.7. But if I created a virtualenv -p /usr/bin/python2.7 and then follow the install, I get errors with modules not being present.

**Comment by smclinden** [comment]
Still having issues. Now it is telling me that flask_login has no module named "mixins".

**Comment by tomchop** [comment]
What method are you using? Can you please share your full setup (systemd scripts, etc).

Also, your PATH-adjusted command should work from a fresh shell (ie no activated virtualenv). If it works, then I see no reason why the service shouldn't

**Comment by smclinden** [comment]
Sure. Followed these instructions (up to and including Download Yeti).

https://github.com/yeti-platform/yeti/blob/master/doc/installation.rst

I, then, did:

% cd yeti
% virtualenv -p /usr/bin/python2.7 venv
% source venv/bin/activate
(venv) % pip install -r requirements.txt
(venv) % yarn install

I, then, tried both setting my PATH to have venv/bin in it, or explicitly calling "yeti.py webserver" with the full path to the venv python.

In both instances I get the same error message:

Traceback (most recent call last):
  File "yeti.py", line 7, in <module>
    from core.web import webapp
  File "/home/cirt/yeti/core/web/__init__.py", line 1, in <module>
    from core.web.webapp import webapp
  File "/home/cirt/yeti/core/web/webapp.py", line 30, in <module>
    auth_module = import_module('core.auth.local')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/cirt/yeti/core/auth/local/__init__.py", line 1, in <module>
    from core.auth.local.views import auth
  File "/home/cirt/yeti/core/auth/local/views.py", line 5, in <module>
    from core.auth.local.user_management import authenticate, create_user, set_password
  File "/home/cirt/yeti/core/auth/local/user_management.py", line 6, in <module>
    from flask_login.mixins import AnonymousUserMixin
ImportError: No module named mixins

**Comment by tomchop** [comment]
Thanks. I'll try to reproduce tomorrow.

**Comment by smclinden** [comment]
I noticed that there appeared to be older versions of flask_login and flask_classy in /usr/local/lib/python2.7 and that pip install did not update these. I ran pip uninstall followed by pip install for both of these and that fixed it. 

Perhaps the installation instructions could be more specific about which versions of these modules are required?

**Comment by tomchop** [comment]
We typically require the "latest" versions of all dependencies to be installed. I could pin them to the requirements.txt file if that makes things clearer, but it might prevent non-conflicting setups to install the full app. We'll consider this, thanks!

**Comment by smclinden** [comment]
Understood. Perhaps it would be enough to simply add a line of text stating the above and recommending that an update be run on any package that pip identifies as previously installed.
