### ISSUE TITLE
Graph not working

### ISSUE THREAD

**Issue by mikelga22** [yeti-platform/yeti#322]
### Description
Graph is not working. When you open the graph of an investigation, or try to create a new one, nodes are not visualized and always says on sidebar "Unamed Investigation", and can not edit it. Also "Quick add" does not work, and you can not add any node.

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | 3a7a54d
| OS version       | Ubuntu 16.04
| Browser          | Chrome 71.0.3578.98

### Steps to Reproduce
1. git clone the repo
1. cd yeti
1. pip install -r requirements
1. python yeti.py webserver

#### Expected behavior
Graph should work

#### Actual behavior
Graph is not working, as said above

**Comment by gaelmuller** [comment]
Could you please provide a screenshot ?

Also, if you open developer tools in Chrome (Ctrl-Shift-J), do you see any errors ?

**Comment by mikelga22** [comment]
Screenshot:
[https://imgur.com/a/eaibwdn](url)

Error:
[https://imgur.com/a/cEOpXZB](url)

Log:
`jquery.min.js:2 jQuery.Deferred exception: e.forEach is not a function TypeError: e.forEach is not a function
    at t.value (http://localhost:5000/static/vis/dist/vis.min.js:42:9816)
    at t.value (http://localhost:5000/static/vis/dist/vis.min.js:42:9407)
    at o.<anonymous> (http://localhost:5000/static/vis/dist/vis.min.js:40:15324)
    at o.i.emit (http://localhost:5000/static/vis/dist/vis.min.js:26:29924)
    at o.setData (http://localhost:5000/static/vis/dist/vis.min.js:40:16728)
    at new o (http://localhost:5000/static/vis/dist/vis.min.js:40:12328)
    at Investigation.toggleLayout (http://localhost:5000/staticfiles/yeti/js/graph.js:949:20)
    at Investigation.initGraph (http://localhost:5000/staticfiles/yeti/js/graph.js:1016:10)
    at new Investigation (http://localhost:5000/staticfiles/yeti/js/graph.js:187:10)
    at HTMLDocument.<anonymous> (http://localhost:5000/investigation/graph/entity/5c33316d3af5ea1f6c916157:669:25) undefined
w.Deferred.exceptionHook @ jquery.min.js:2
content.min.js:2 [Deprecation] Element.createShadowRoot is deprecated and will be removed in M73, around March 2019. Please use Element.attachShadow instead. See https://www.chromestatus.com/features/4507242028072960 for more details.
(anonymous) @ content.min.js:2
jquery.min.js:2 Uncaught TypeError: e.forEach is not a function
    at t.value (vis.js:47786)
    at t.value (vis.js:47741)
    at o.<anonymous> (vis.js:42725)
    at o.i.emit (vis.js:6529)
    at o.setData (vis.js:42786)
    at new o (vis.js:42571)
    at Investigation.toggleLayout (graph.js:949)
    at Investigation.initGraph (graph.js:1016)
    at new Investigation (graph.js:187)
    at HTMLDocument.<anonymous> (5c33316d3af5ea1f6c916157:669)`

**Comment by mikelga22** [comment]
I do not why, but now it apparently works
