### ISSUE TITLE
URL observables that contain a comma fail to update.

### ISSUE THREAD

**Issue by phage-nz** [yeti-platform/yeti#342]
Following on from the discussion on the Yeti Slack, I've observed feeds failing to pull where an ingested URL has a comma in it. This appears to be due to improper normalisation.

Here's the stack trace of a failure:
```
Feb 19 17:22:51 yeti celery[1133]: [2019-02-19 17:22:51,511: ERROR/ForkPoolWorker-4] Traceback (most recent call last):
Feb 19 17:22:51 yeti celery[1133]:   File "/opt/yeti/core/feed.py", line 42, in update_feed
Feb 19 17:22:51 yeti celery[1133]:     f.update()
Feb 19 17:22:51 yeti celery[1133]:   File "/opt/yeti/plugins/feeds/public/phishtank.py", line 26, in update
Feb 19 17:22:51 yeti celery[1133]:     self.analyze(line)
Feb 19 17:22:51 yeti celery[1133]:   File "/opt/yeti/plugins/feeds/public/phishtank.py", line 55, in analyze
Feb 19 17:22:51 yeti celery[1133]:     url = Url.get_or_create(value=url)
Feb 19 17:22:51 yeti celery[1133]:   File "/opt/yeti/core/database.py", line 94, in get_or_create
Feb 19 17:22:51 yeti celery[1133]:     obj = cls.objects.get(**select_dict)
Feb 19 17:22:51 yeti celery[1133]:   File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py", line 286, in get
Feb 19 17:22:51 yeti celery[1133]:     raise queryset._document.MultipleObjectsReturned(message)
Feb 19 17:22:51 yeti celery[1133]: MultipleObjectsReturned: 22 items returned, instead of 1
Feb 19 17:22:51 yeti celery[1133]: [2019-02-19 17:22:51,516: ERROR/ForkPoolWorker-4] ERROR updating feed: 22 items returned, instead of 1
```

I managed to address this by URL encoding commas in the refang method:
```
def refang(url):
   def http(match):
       return "http{}".format(match.group('real'))
   substitutes = ('me[o0]w', 'h..p')
   schema_re = re.compile(
       "^(?P<fake>{})(?P<real>s?://)".format("|".join(substitutes)))
   domain_re = re.compile(r"(\[\.\]|,)")
   url = url.replace(',', '%2C')
   url = schema_re.sub(http, url)
   print('Schema RE Complete: {0}'.format(url))
   url = domain_re.sub(".", url)
   print('Domain RE Complete: {0}'.format(url))
   return url
```

Failures that were occurring for CleanMX, OpenPhish, PhishTank and URLhaus now no longer occur.

**Comment by tomchop** [comment]
FTR, this is being worked on in https://github.com/yeti-platform/yeti/pull/353
