### ISSUE TITLE
Failed to install yeti requirements

### ISSUE THREAD

**Issue by PersonalizedFinances** [yeti-platform/yeti#345]
Before opening an issue, please make do a quick search through the current issues
and the mailing list (https://groups.google.com/forum/#!forum/yeti-users) to see
if it hasn't been answered already.

### Description
I am getting error during yeti requirement installation step. Please help.

### Environment

| Question         | Answer
|------------------|--------------------
| OS version       | Ubuntu 16.04 

### Steps to Reproduce
1. sudo apt-get install build-essential git python-dev mongodb redis-server libxml2-dev libxslt-dev zlib1g-dev python-virtualenv wkhtmltopdf
2. curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
3. echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
4. sudo apt-get update && sudo apt-get install yarn
5. git clone https://github.com/yeti-platform/yeti.git
6. cd yeti
7. pip install -r requirements.txt

#### Expected behavior
I am expecting that yeti requirements be installed.

#### Actual behavior
It throws following error:
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 305, in run
    wheel_cache
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 291, in populate_requirement_set
    requirement_set.add_requirement(req)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 224, in add_requirement
    if not install_req.match_markers():
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 823, in match_markers
    return Marker(self.markers).evaluate()
  File "/usr/share/python-wheels/packaging-16.6-py2.py3-none-any.whl/packaging/markers.py", line 278, in evaluate
    return _evaluate_markers(self._markers, current_environment)
  File "/usr/share/python-wheels/packaging-16.6-py2.py3-none-any.whl/packaging/markers.py", line 203, in _evaluate_markers
    lhs_value = _get_env(environment, lhs.value)
  File "/usr/share/python-wheels/packaging-16.6-py2.py3-none-any.whl/packaging/markers.py", line 185, in _get_env
    "{0!r} does not exist in evaluation environment.".format(name)
UndefinedEnvironmentName: 'extra' does not exist in evaluation environment.

**Comment by tomchop** [comment]
Seems to be related an ubuntu packaging error for pip; check out https://github.com/getsentry/sentry/issues/3143 for possible solutions.

Try upgrading your pip version before installing the requirements?

**Comment by PersonalizedFinances** [comment]
Thank you a lot. Upgrading to the last pip version solved this issue.
