### ISSUE TITLE
Randomly Unable to Upload Observables

### ISSUE THREAD

**Issue by mshelton** [yeti-platform/yeti#43]
### Description
Yeti is throwing an exception when we attempt to upload observables.  We are having difficulties identifying the commonalities between the observables that fail and the observables that work.  We believe it might be associated with uploading large numbers of duplicate observables.

Has anyone seen this exception before?

```
Apr  4 14:56:27 <hostname> uwsgi[13723]: [2017-04-04 14:56:27,095] ERROR in app: Exception on /observable/ [POST]
Apr  4 14:56:27 <hostname> uwsgi[13723]: Traceback (most recent call last):
Apr  4 14:56:27 <hostname> uwsgi[13723]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
Apr  4 14:56:27 <hostname> uwsgi[13723]:     response = self.full_dispatch_request()
Apr  4 14:56:27 <hostname> uwsgi[13723]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
Apr  4 14:56:27 <hostname> uwsgi[13723]:     rv = self.handle_user_exception(e)
Apr  4 14:56:27 <hostname> uwsgi[13723]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
Apr  4 14:56:27 <hostname> uwsgi[13723]:     reraise(exc_type, exc_value, tb)
Apr  4 14:56:27 <hostname> uwsgi[13723]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
Apr  4 14:56:27 <hostname> uwsgi[13723]:     rv = self.dispatch_request()
Apr  4 14:56:27 <hostname> uwsgi[13723]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
Apr  4 14:56:27 <hostname> uwsgi[13723]:     return self.view_functions[rule.endpoint](**req.view_args)
Apr  4 14:56:27 <hostname> uwsgi[13723]:   File "/usr/local/lib/python2.7/dist-packages/flask_classy.py", line 200, in proxy
Apr  4 14:56:27 <hostname> uwsgi[13723]:     response = view(**request.view_args)
Apr  4 14:56:27 <hostname> uwsgi[13723]:   File "./core/web/helpers.py", line 32, in inner
Apr  4 14:56:27 <hostname> uwsgi[13723]:     return f(*args, **kwargs)
Apr  4 14:56:27 <hostname> uwsgi[13723]:   File "./core/web/frontend/observables.py", line 87, in index
Apr  4 14:56:27 <hostname> uwsgi[13723]:     o = Observable.add_text(txt)
Apr  4 14:56:27 <hostname> uwsgi[13723]:   File "./core/observables/observable.py", line 105, in add_text
Apr  4 14:56:27 <hostname> uwsgi[13723]:     o = Observable.guess_type(text).get_or_create(value=text)
Apr  4 14:56:27 <hostname> uwsgi[13723]:   File "./core/database.py", line 297, in get_or_create
Apr  4 14:56:27 <hostname> uwsgi[13723]:     return cls.objects.get(value=obj.value)
Apr  4 14:56:27 <hostname> uwsgi[13723]:   File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py", line 271, in get
Apr  4 14:56:27 <hostname> uwsgi[13723]:     raise queryset._document.DoesNotExist(msg)
Apr  4 14:56:27 <hostname> uwsgi[13723]: DoesNotExist: Observable.Ip matching query does not exist.
```
 
### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | 27ae09f83b0165c36c78297708b4a2e75c9a2dad
| OS version       | Ubuntu 16.04
| Browser          | Chrome 56.0.2924.87

### Steps to Reproduce
1. Upload more than 10 observables
1. Upload them again

#### Expected behavior
Observables should be inserted into Yeti

#### Actual behavior
We are receiving an "500 Internal Server Error" instead

**Comment by tomchop** [comment]
That's interesting. I've seen this in the past, it was because of some bug in the normalization of observables (happened a lot with URLs). 

Is there any way you can (privately, if need be) share the list of observables that triggers the bug?

**Comment by mshelton** [comment]
Yes!  I can privately share the indicators.  Where do you want me to send them?

**Comment by tomchop** [comment]
Please send them over to tomchop@gmail.com, I'll have a look.

**Comment by tomchop** [comment]
It turns out this was due to all Observables being inserted as "Text" rather than their true types. When Yeti attempted to insert an observable of identical value, it would turn out present in the database but not as the correct type, hence the exception.

We need to find a way to make this more user-friendly.
