### ISSUE TITLE
"{} was not recognized as a viable datatype".format(string)) - Regular expression

### ISSUE THREAD

**Issue by clp-trap** [yeti-platform/yeti#453]
### Description

Getting the following while running a search on observable that has a regular expression rule to it:

"{} was not recognized as a viable datatype".format(string))

### Environment
Same error on Centos and Ubuntu

### Steps to Reproduce
Essentially it mimics detection of a mutex string/guid

1. Create a simple regular expression rule:
[a-z0-9]{20}
2. Run any string that matches the above:
5ddfdf34324324234234

I presume it's related to the fact that there is no "Text" observable in the following snippet:

for t in [Url, Ip, Email, Path, Hostname, Hash, Bitcoin, MacAddress]:

**Comment by doomedraven** [comment]
can you post please a bit of log or something? to know where exactly that happens

**Comment by clp-trap** [comment]
@doomedraven sure:

Traceback (most recent call last)
File "/home/myuser/.local/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
	return self.wsgi_app(environ, start_response)
File "/home/myuser/.local/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
	response = self.handle_exception(e)
File "/home/myuser/.local/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
	reraise(exc_type, exc_value, tb)
File "/home/myuser/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
	response = self.full_dispatch_request()
File "/home/myuser/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
	rv = self.handle_user_exception(e)
File "/home/myuser/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
	reraise(exc_type, exc_value, tb)
File "/home/myuser/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
	rv = self.dispatch_request()
File "/home/myuser/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
	return self.view_functions[rule.endpoint](**req.view_args)
File "/home/myuser/.local/lib/python2.7/site-packages/flask_classy.py", line 200, in proxy
	response = view(**request.view_args)
	File "/home/myuser/yeti/core/web/helpers.py", line 37, in inner
return f(*args, **kwargs)
	File "/home/myuser/yeti/core/web/frontend/observables.py", line 111, in index
	data = match_observables(obs.keys())
File "/home/myuser/yeti/core/analysis.py", line 107, in match_observables
	o = Observable.guess_type(o)(value=o)
	File "/home/myuser/yeti/core/observables/observable.py", line 108, in guess_type
	"{} was not recognized as a viable datatype".format(string))

ObservableValidationError: 5ddfdf34324324234234 was not recognized as a viable datatype

**Comment by doomedraven** [comment]
ah ok make sense, thanks for log, now that makes sense, i would suggest you to create a new observable type maybe, not sure, not enough coffee yet xD

**Comment by clp-trap** [comment]
Thanks, will try 👍

**Comment by doomedraven** [comment]
check asn type is pretty simple :) https://github.com/yeti-platform/yeti/blob/master/core/observables/ip.py

**Comment by clp-trap** [comment]
Thanks, when adding observables through the UI search and add screen, there is a "Text" guess type that's why I thought this type exists

**Comment by clp-trap** [comment]
@doomedraven importing "Text" and adding it to the for loop did the magic:

        from core.observables import Url, **File**, Ip, Email, Path, Hostname, Hash, Bitcoin, MacAddress
        if string and string.strip() != '':
            for t in [Url, **File**, Ip, Email, Path, Hostname, Hash, Bitcoin, MacAddress]:
                if t.check_type(string):
                    return t
