### ISSUE TITLE
BuildError: Could not build url for endpoint u'api.UserAdmin:post' with values ['id']. Did you mean u'api.UserAdminSearch:post' instead?

### ISSUE THREAD

**Issue by zahid1121** [yeti-platform/yeti#484]
I moved on Investigations>Import and write a hash (in import from text)
after starting import i found a hash in left panel. after clicking on import i found the following exception. 

SON([('_id', ObjectId('5d3e9e4b9e11b00cca507544')), ('attached_files', []), ('links', []), ('nodes', [SON([('_id', ObjectId('5d3e9ca47cfa1628361ecb0a')), ('_cls', u'Observable.Hash'), ('attached_files', []), ('value', u'9216b29114fb6713ef228370cbfe4044'), ('sources', []), ('context', []), ('tags', [SON([('name', u'wwwww'), ('first_seen', datetime.datetime(2019, 7, 29, 7, 15, 30, 311000)), ('last_seen', datetime.datetime(2019, 7, 29, 7, 15, 30, 311000)), ('expiration', 7776000.0), ('fresh', True)])]), ('last_analyses', {}), ('created', datetime.datetime(2019, 7, 29, 7, 13, 40, 371000)), ('last_tagged', datetime.datetime(2019, 7, 29, 7, 15, 30, 313000)), ('family', u'md5')])]), ('events', [SON([('kind', u'add'), ('links', []), ('nodes', [ObjectId('5d3e9ca47cfa1628361ecb0a')]), ('datetime', datetime.datetime(2019, 7, 29, 7, 20, 46, 756000))])]), ('created_by', u'yeti'), ('created', datetime.datetime(2019, 7, 29, 7, 20, 43, 954000)), ('updated', datetime.datetime(2019, 7, 29, 7, 20, 46, 757000)), ('import_text', u'9216b29114fb6713ef228370cbfe4044'), ('tags', []), ('sharing', [ObjectId('5d3adaee9e11b053790cb4d2')]), (u'shared', [<User: <User: yeti>>])])
Traceback (most recent call last):
  File "/home/internet/.local/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/internet/.local/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/internet/.local/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/internet/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/internet/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/internet/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/internet/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/internet/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/internet/.local/lib/python2.7/site-packages/flask_classy.py", line 200, in proxy
    response = view(**request.view_args)
  File "/home/internet/yeti/core/web/helpers.py", line 39, in inner
    return f(*args, **kwargs)
  File "/home/internet/yeti/core/web/frontend/investigations.py", line 32, in graph
    investigation=bson_renderer(investigation.info()))
  File "/home/internet/.local/lib/python2.7/site-packages/flask_negotiation/renderers.py", line 99, in __call__
    return self.render(*args, **kwargs)
  File "/home/internet/.local/lib/python2.7/site-packages/flask_negotiation/renderers.py", line 96, in render
    return self.fn(data, template=template, ctx=ctx)
  File "/home/internet/yeti/core/web/api/api.py", line 21, in bson_renderer
    data = recursive_encoder(objects)
  File "/home/internet/yeti/core/web/json.py", line 18, in recursive_encoder
    objects[key] = recursive_encoder(value)
  File "/home/internet/yeti/core/web/json.py", line 22, in recursive_encoder
    return [recursive_encoder(o) for o in objects]
  File "/home/internet/yeti/core/web/json.py", line 30, in recursive_encoder
    data = objects.info()
  File "/home/internet/yeti/core/user.py", line 90, in info
    "api.UserAdmin:post", id=str(self.id), _external=True)
  File "/home/internet/.local/lib/python2.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/internet/.local/lib/python2.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/internet/.local/lib/python2.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/internet/.local/lib/python2.7/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint u'api.UserAdmin:post' with values ['id']. Did you mean u'api.UserAdminSearch:post' instead?

What should I do now?

**Comment by doomedraven** [comment]
@tomchop did you change something else? i don't have this error and import works fine hm
if i will have some spare time i will check how it diff fron my original pr

**Comment by zahid1121** [comment]
Thanks @doomedraven 
Importing from URL works fine for me. The only issue I got in importing from text in which only a hash of a file is provided.

**Comment by doomedraven** [comment]
yep i see, i think i know what is the difference and cause this, in my production i have users managment but i still didn't have `investigation=bson_renderer(investigation.info()))` <- that info PR not merged and not deployed on my side, so there should be the overlap problem

**Comment by tomchop** [comment]
I'll have a look at this in a few hours.

**Comment by tomchop** [comment]
Should be fixed now! @zahid1121, can you give it another go?

**Comment by zahid1121** [comment]
Yes. Its working now. thanks :+1:
