### ISSUE TITLE
IOError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by zahid1121** [yeti-platform/yeti#486]
Getting following exception on 
Investigations>[Node Name]>Action>Analytics

ERROR:_internal:Error on request:
Traceback (most recent call last):
  File "/home/internet/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/home/internet/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/home/internet/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 227, in write
    self.send_header(key, value)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 412, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe
ERROR:_internal:Error on request:
Traceback (most recent call last):
  File "/home/internet/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/home/internet/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/home/internet/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 227, in write
    self.send_header(key, value)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 412, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe
ERROR:_internal:Error on request:
Traceback (most recent call last):
  File "/home/internet/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/home/internet/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/home/internet/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 227, in write
    self.send_header(key, value)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 412, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe

Would you please help me to solve this?

**Comment by tomchop** [comment]
Can you please detail what you are doing to get this error?

**Comment by zahid1121** [comment]
Actually I am trying to search for an IP address. For that, I followed the way,
Investigations>Import>
and then I wrote IP address in "import from text" section and started import. 
after that, I moved to "go to graph", selected the node of IP address and moved to actions. there, I am searching it on all modules in Analytics and getting the above exception.

**Comment by zahid1121** [comment]
at this time, I got the exception too..

SON([('_id', ObjectId('5d3fdbcd9e11b0317fd261ff')), ('attached_files', []), ('name', u'tgvgtv'), ('description', u'tfstf'), ('links', []), ('nodes', [SON([('_id', ObjectId('5d3fdbfb7cfa1628362232e2')), ('_cls', u'Observable.Ip'), ('attached_files', []), ('value', u'145.44.42.5'), ('sources', []), ('context', []), ('tags', []), ('last_analyses', {}), ('created', datetime.datetime(2019, 7, 30, 5, 56, 11, 34000)), ('geoip', {}), ('version', 4)])]), ('events', [SON([('kind', u'add'), ('links', []), ('nodes', [ObjectId('5d3fdbfb7cfa1628362232e2')]), ('datetime', datetime.datetime(2019, 7, 30, 5, 57, 32, 24000))])]), ('created_by', u'yeti'), ('created', datetime.datetime(2019, 7, 30, 5, 55, 25, 511000)), ('updated', datetime.datetime(2019, 7, 30, 5, 57, 32, 25000)), ('tags', [u'unknown']), ('sharing', [ObjectId('5d3adaee9e11b053790cb4d2')]), (u'shared', [<User: <User: yeti>>])])
ERROR:app:Exception on /api/investigation/search_existence [POST]
Traceback (most recent call last):
  File "/home/internet/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/internet/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/internet/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/internet/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/internet/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/internet/.local/lib/python2.7/site-packages/flask_classy.py", line 200, in proxy
    response = view(**request.view_args)
  File "/home/internet/yeti/core/web/helpers.py", line 39, in inner
    return f(*args, **kwargs)
  File "/home/internet/yeti/core/web/api/investigation.py", line 171, in search_existence
    return render(response)
  File "/home/internet/.local/lib/python2.7/site-packages/flask_negotiation/__init__.py", line 76, in __call__
    body = renderer.render(data, template, ctx)
  File "/home/internet/.local/lib/python2.7/site-packages/flask_negotiation/renderers.py", line 96, in render
    return self.fn(data, template=template, ctx=ctx)
  File "/home/internet/yeti/core/web/api/api.py", line 22, in bson_renderer
    return dumps(data, default=to_json)
  File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/home/internet/yeti/core/web/json.py", line 49, in to_json
    return default(obj)
  File "/home/internet/.local/lib/python2.7/site-packages/bson/json_util.py", line 857, in default
    raise TypeError("%r is not JSON serializable" % obj)
TypeError: <User: <User: yeti>> is not JSON serializable

**Comment by doomedraven** [comment]
@tomchop looks like this failing
`('sharing', [ObjectId('5d3adaee9e11b053790cb4d2')]), (u'shared', [<User: <User: yeti>>])])`
so there should be another change to my original PR by someone else

**Comment by zahid1121** [comment]
@doomedraven 
Need help regarding the issue

**Comment by doomedraven** [comment]
well you can replace it by yourself https://github.com/yeti-platform/yeti/blob/master/core/investigation.py#L88

* mine
```
    def info(self):
        result = self.to_mongo()
        result['nodes'] = [node.to_mongo() for node in self.nodes if hasattr(node, "to_mongo")]
        try:
            result["shared"] = [Group(id=shared_with_id).reload() for shared_with_id in Investigation.objects.get(id=self.id).sharing]
        except Exception as e:
            logging.info(e)
        return result
```

* upstream

```
    def info(self):
        result = self.to_mongo()
        result['nodes'] = [node.to_mongo() for node in self.nodes]
        shared = []
        for sharing_id in Investigation.objects.get(id=self.id).sharing:
            try:
                shared.append(Group.objects.get(id=sharing_id))
            except:
                try:
                    shared.append(User.objects.get(id=sharing_id))
                except:
                    pass
        if shared:
            result['shared'] = shared
        print result
        return result
```

**Comment by zahid1121** [comment]
I am Periodically getting the error, Is it related to the same issue?

> Exception happened during processing of request from ('127.0.0.1', 46098)
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
>     self.finish_request(request, client_address)
>   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
>     self.finish()
>   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
>     self.wfile.close()
>   File "/usr/lib/python2.7/socket.py", line 283, in close
>     self.flush()
>   File "/usr/lib/python2.7/socket.py", line 307, in flush
>     self._sock.sendall(view[write_offset:write_offset+buffer_size])
> error: [Errno 32] Broken pipe

**Comment by doomedraven** [comment]
no that isn't related at all

**Comment by zahid1121** [comment]
Thanks. your solution worked for 

> TypeError: <User: <User: yeti>> is not JSON serializable
