### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by phaag** [yeti-platform/yeti#543]
Hi,
I am get very often 500 Internal Server Error at random places, when selecting a menu or saving an entry. It's always the same kind of traceback:

```
==> ../syslog <==
Dec 17 10:45:05 argon uwsgi[2152]: INFO:user_management:Default user logged in : yeti
Dec 17 10:45:05 argon uwsgi[2152]: ERROR:app:Exception on /entity/5df8aed98b51a7094d8d8f12 [GET]
Dec 17 10:45:05 argon uwsgi[2152]: Traceback (most recent call last):
Dec 17 10:45:05 argon uwsgi[2152]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
Dec 17 10:45:05 argon uwsgi[2152]:     response = self.full_dispatch_request()
Dec 17 10:45:05 argon uwsgi[2152]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
Dec 17 10:45:05 argon uwsgi[2152]:     rv = self.handle_user_exception(e)
Dec 17 10:45:05 argon uwsgi[2152]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
Dec 17 10:45:05 argon uwsgi[2152]:     reraise(exc_type, exc_value, tb)
Dec 17 10:45:05 argon uwsgi[2152]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
Dec 17 10:45:05 argon uwsgi[2152]:     rv = self.dispatch_request()
Dec 17 10:45:05 argon uwsgi[2152]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
Dec 17 10:45:05 argon uwsgi[2152]:     return self.view_functions[rule.endpoint](**req.view_args)
Dec 17 10:45:05 argon uwsgi[2152]:   File "/usr/local/lib/python2.7/dist-packages/flask_classy.py", line 200, in proxy
Dec 17 10:45:05 argon uwsgi[2152]:     response = view(**request.view_args)
Dec 17 10:45:05 argon uwsgi[2152]:   File "./core/web/helpers.py", line 37, in inner
Dec 17 10:45:05 argon uwsgi[2152]:     # improve this and make it redirect to login
Dec 17 10:45:05 argon uwsgi[2152]:   File "./core/web/frontend/generic.py", line 36, in get
Dec 17 10:45:05 argon uwsgi[2152]:     if hasattr(obj, "sharing"):
Dec 17 10:45:05 argon uwsgi[2152]:   File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 135, in render_template
Dec 17 10:45:05 argon uwsgi[2152]:     context, ctx.app)
Dec 17 10:45:05 argon uwsgi[2152]:   File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 117, in _render
Dec 17 10:45:05 argon uwsgi[2152]:     rv = template.render(context)
Dec 17 10:45:05 argon uwsgi[2152]:   File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
Dec 17 10:45:05 argon uwsgi[2152]:     return self.environment.handle_exception(exc_info, True)
Dec 17 10:45:05 argon uwsgi[2152]:   File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
Dec 17 10:45:05 argon uwsgi[2152]:     reraise(exc_type, exc_value, tb)
Dec 17 10:45:05 argon uwsgi[2152]:   File "/opt/yeti/core/web/frontend/templates/entity/single.html", line 8, in top-level template code
Dec 17 10:45:05 argon uwsgi[2152]:     {% import "macros/observables.html" as observables %}
Dec 17 10:45:05 argon uwsgi[2152]:   File "/opt/yeti/core/web/frontend/templates/base.html", line 171, in top-level template code
Dec 17 10:45:05 argon uwsgi[2152]:     <li><a href="{{ url_for('frontend.GroupAdminView:index') }}">Group administration</a></li>
Dec 17 10:45:05 argon uwsgi[2152]:   File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 356, in url_for
Dec 17 10:45:05 argon uwsgi[2152]:     return appctx.app.handle_url_build_error(error, endpoint, values)
Dec 17 10:45:05 argon uwsgi[2152]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2061, in handle_url_build_error
Dec 17 10:45:05 argon uwsgi[2152]:     reraise(exc_type, exc_value, tb)
Dec 17 10:45:05 argon uwsgi[2152]:   File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 345, in url_for
Dec 17 10:45:05 argon uwsgi[2152]:     force_external=external)
Dec 17 10:45:05 argon uwsgi[2152]:   File "/usr/local/lib/python2.7/dist-packages/werkzeug/routing.py", line 1776, in build
Dec 17 10:45:05 argon uwsgi[2152]:     raise BuildError(endpoint, values, method, self)
Dec 17 10:45:05 argon uwsgi[2152]: BuildError: Could not build url for endpoint 'frontend.GroupAdminView:index'. Did you mean u'frontend.UserAdminView:index' instead?

```
Sometime a shift-reload helps, but not always. 

Any help is appreciated.

**Comment by tomchop** [comment]
Very weird that you get this intermittently. Can you please tell me which commit version you're using?

**Comment by phaag** [comment]
It's the git pull from this morning. Running all on Ubuntu 18.04 LTS.

**Comment by phaag** [comment]
The strange thing is, that it happens approx. every 20th mouse clicks ..

**Comment by sebdraven** [comment]
I close this issue, if you have the same trouble, don't hesitate to re open it !
