### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by psychomad** [yeti-platform/yeti#57]
### Description
All step was fine until i start python2 yeti.py (tried also ./yeti.py)
[+] Yeti started. Point browser to http://localhost:5000/
Any clue?
When i try to open page all the noise come up:

ERROR:core.web.webapp:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1473, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1666, in preprocess_request
    rv = func()
  File "/home/docplague/Scrivania/arsenale/yeti/core/web/webapp.py", line 53, in frontend_login_required
    if not current_user.is_active and (request.endpoint and request.endpoint != 'frontend.static'):
  File "/usr/lib/python2.7/dist-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/lib/python2.7/dist-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 302, in _get_user
    current_app.login_manager._load_user()
  File "/usr/local/lib/python2.7/dist-packages/flask_login/login_manager.py", line 313, in _load_user
    return self._load_from_request(request)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/login_manager.py", line 370, in _load_from_request
    user = self.request_callback(request)
  File "/home/docplague/Scrivania/arsenale/yeti/core/web/webapp.py", line 44, in api_auth
    return User.objects.get(api_key=request.headers.get('X-Api-Key'))
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/manager.py", line 37, in __get__
    queryset = queryset_class(owner, owner._get_collection())
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/document.py", line 206, in _get_collection
    cls.ensure_indexes()
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/document.py", line 836, in ensure_indexes
    collection.create_index(fields, background=background, **opts)
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 1529, in create_index
    self.__create_index(keys, kwargs)
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 1417, in __create_index
    with self._socket_for_writes() as sock_info:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 823, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/usr/lib/python2.7/dist-packages/pymongo/topology.py", line 214, in select_server
    address))
  File "/usr/lib/python2.7/dist-packages/pymongo/topology.py", line 189, in select_servers
    self._error_message(selector))
ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused

### Environment

Debian 8.5

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log | head -n1` to find out
| OS version       | Ubuntu 16.04, Windows 10, macOS 10.12.3
| Browser          | Chrome 56.0.2924.87

### Steps to Reproduce
1. git clone the repo
1. cd yeti
1. pip install -r
1. observe stacktrace

#### Expected behavior
[How are you expecting the application to behave?]

#### Actual behavior
[How is the application behaving? (include any stacktraces, logs, screenshots, etc.)]

**Comment by tomchop** [comment]
Looks like `mongo` is not running. Can you please make sure it's running and listening for connections on the default port?

**Comment by remotephone** [comment]
Any chance you're doing this in a VM? I did it in a VM with a small drive (10gb but other stuff on it) and mongo wouldn't start. I had to manually start it in a separate terminal with "mongod --dbpath /opt/yeti --smallfiles" and the Yeti interface loaded.

**Comment by psychomad** [comment]
Hi sorry for delay.
I heked and mongodb was installed and active, i checked with ps aux and so on.
Was launched not in VM but on a debian 8.x
still the same problem... no clue

**Comment by boarterwarding** [comment]
I faced a similar issue on a fresh Debian install on a VM. I solved the problem by su'ing into root
'su' and then running 'mkdir /opt/yeti'. Manually starting mongodb by running 'mongod --dbpath /opt/yeti --smallfiles' in a separate terminal windows before starting Yeti does the trick for me.

**Comment by tomchop** [comment]
`ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused` really sounds like a socket level error. Does running with `--smallfiles` fix your problem?

**Comment by gaelmuller** [comment]
Closing this issue since there was no answer to last comment. Do not hesitate to reopen if needed.
