### ISSUE TITLE
python2 -> python3 upgrade guide?

### ISSUE THREAD

**Issue by villain** [yeti-platform/yeti#603]
uwsgi after python 3 upgrade is producing an 'Internal Server Error' in small text

bypassing the uwsgi and going straight to http://yeti:5000 appears to be fine

i've tried uninstalling and reinstalling uwsgi to no avail

any ideas?

**Comment by villain** [comment]
related to this it seems:

Jul 12 11:16:16 yeti uwsgi[3122]: Traceback (most recent call last):
Jul 12 11:16:16 yeti uwsgi[3122]:   File "./yeti.py", line 7, in <module>
Jul 12 11:16:16 yeti uwsgi[3122]:     from core.web import webapp
Jul 12 11:16:16 yeti uwsgi[3122]:   File "./core/__init__.py", line 4, in <module>
Jul 12 11:16:16 yeti uwsgi[3122]:     from core.exports import Export
Jul 12 11:16:16 yeti uwsgi[3122]:   File "./core/exports/__init__.py", line 1, in <module>
Jul 12 11:16:16 yeti uwsgi[3122]:     from core.exports.export import ExportTemplate
Jul 12 11:16:16 yeti uwsgi[3122]:   File "./core/exports/export.py", line 17, in <module>
Jul 12 11:16:16 yeti uwsgi[3122]:     from core.observables import Observable, Tag
Jul 12 11:16:16 yeti uwsgi[3122]:   File "./core/observables/__init__.py", line 6, in <module>
Jul 12 11:16:16 yeti uwsgi[3122]:     from core.observables.url import Url
Jul 12 11:16:16 yeti uwsgi[3122]:   File "./core/observables/url.py", line 4, in <module>
Jul 12 11:16:16 yeti uwsgi[3122]:     from urllib.parse import urlparse

but this works fine:
python3
from urllib.parse import urlparse

**Comment by villain** [comment]
alrighty, for anyone having issues upgrading to the latest yeti, going from python2 -> python3 on ubuntu, you likely have uwsgi installed via apt and not pip (pip3). remove the apt version and pip3 install uwsgi and you're good to go
