### ISSUE TITLE
Failed to establish a new connection

### ISSUE THREAD

**Issue by mfiedler144** [yeti-platform/yeti#635]
Hello everyone, 

I chose Yeti for the tool i want to use in my research project. So i started the installation today via the documentation but can't get any further and need your help. I followed along until the quick and dirty part, started the websever and the workers (I did not the bootstrapping part). 

### Description
I am not able to connect to the feed source and not able to pull the data. 

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | commit c6bd7246c5472c02112564af2e294b9b0a9d12a9
| OS version       | Ubuntu 20.04.1 LTS
| Browser          | Chrome Version 87.0.4280.66 (Official Build) (64-bit)

### Steps to Reproduce
1. Start MongoDB
2. Start Redis
3. Start Worker
4. Start Sheduler
5. Start Webserver
6. Go in the DataFlow menue
7. Refresh the feed (standard feeds, which are already ready to use)

#### Expected behavior
It should connect and pull the feed-data.

#### Actual behavior
Failed to establish a new connection: Errno -2

`INFO:user_management:Default user logged in : yeti
INFO:_internal:127.0.0.1 - - [30/Dec/2020 17:49:38] "POST /api/feed/5fec7bd2729587f618fa0c88/refresh HTTP/1.1" 200 -
[2020-12-30 17:49:38,380: ERROR/ForkPoolWorker-1] Traceback (most recent call last):
  File "/home/mdev/dev/.envs/yeti/lib/python3.8/site-packages/urllib3/connection.py", line 156, in _new_conn
    conn = connection.create_connection(
  File "/home/mdev/dev/.envs/yeti/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mdev/dev/.envs/yeti/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/home/mdev/dev/.envs/yeti/lib/python3.8/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/home/mdev/dev/.envs/yeti/lib/python3.8/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/home/mdev/dev/.envs/yeti/lib/python3.8/site-packages/urllib3/connection.py", line 300, in connect
    conn = self._new_conn()
  File "/home/mdev/dev/.envs/yeti/lib/python3.8/site-packages/urllib3/connection.py", line 168, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f3d5a07e7c0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mdev/dev/.envs/yeti/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/mdev/dev/.envs/yeti/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/home/mdev/dev/.envs/yeti/lib/python3.8/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='feodotracker.abuse.ch', port=443): Max retries exceeded with url: /downloads/ipblocklist.csv (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3d5a07e7c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mdev/dev/ioc-analysis/yeti/core/feed.py", line 52, in update_feed
    f.update()
  File "/home/mdev/dev/ioc-analysis/yeti/plugins/feeds/public/feodo_tracker_ip_blocklist.py", line 19, in update
    for index, line in self.update_csv(
  File "/home/mdev/dev/ioc-analysis/yeti/core/feed.py", line 482, in update_csv
    r = self._make_request(sort=False, headers=headers, auth=auth, verify=verify)
  File "/home/mdev/dev/ioc-analysis/yeti/core/feed.py", line 354, in _make_request
    r = getattr(requests, method)(
  File "/home/mdev/dev/.envs/yeti/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/mdev/dev/.envs/yeti/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/mdev/dev/.envs/yeti/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mdev/dev/.envs/yeti/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/mdev/dev/.envs/yeti/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='feodotracker.abuse.ch', port=443): Max retries exceeded with url: /downloads/ipblocklist.csv (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3d5a07e7c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

[2020-12-30 17:49:38,475: ERROR/ForkPoolWorker-1] ERROR updating feed: HTTPSConnectionPool(host='feodotracker.abuse.ch', port=443): Max retries exceeded with url: /downloads/ipblocklist.csv (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3d5a07e7c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))`

**Comment by dumprop** [comment]
Seems like no connection to feodotracker.abuse.ch
Try that in terminal: curl https://feodotracker.abuse.ch/downloads/ipblocklist.csv
Do you have any results? This problem with all feeds or only feodotracker.abuse.ch?

**Comment by mfiedler144** [comment]
Hi thanks, that helped a lot. After the curl I got a proxy error and was able to fix the problem.
