### ISSUE TITLE
testfeed.py Not Working

### ISSUE THREAD

**Issue by Tom-Gorup** [yeti-platform/yeti#64]
### Description
Having an issue with `testfeed.py` where it seems to hang on a connection to Redis.

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | 0ece661ab7b37c7f95a63302a28cba19051b8adf
| OS version       | No LSB modules are available.
|                          | Distributor ID:	Ubuntu
|                          | Description:	Ubuntu 16.04.2 LTS
|                          | Release:	16.04
|                          | Codename:	xenial
| Browser          | Chrome 56.0.2924.87

#### netstat -ntlp
| Proto | Recv-Q | Send-Q | Local Address           | Foreign Address         | State       | PID/Program name
|------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------
| tcp        | 0      | 0 | 127.0.0.1:8126          | 0.0.0.0:*               | LISTEN      | 1429/trace-agent
| tcp        | 0      | 0 | 127.0.0.1:8000          | 0.0.0.0:*               | LISTEN      | 1208/uwsgi
| tcp        | 0      | 0 | 127.0.0.1:7777          | 0.0.0.0:*               | LISTEN      | 1429/trace-agent
| tcp        | 0      | 0 | 127.0.0.1:17123         | 0.0.0.0:*               | LISTEN      | 1430/python
| tcp        | 0      | 0 | 127.0.0.1:9191          | 0.0.0.0:*               | LISTEN      | 1208/uwsgi
| tcp        | 0      | 0 | 0.0.0.0:5000            | 0.0.0.0:*               | LISTEN      | 1214/python
| tcp        | 0      | 0 | 127.0.0.1:27017         | 0.0.0.0:*               | LISTEN      | 1092/mongod
| tcp        | 0      | 0 | 127.0.0.1:6379          | 0.0.0.0:*               | LISTEN      | 1179/redis-server 1
| tcp        | 0      | 0 | 0.0.0.0:80              | 0.0.0.0:*               | LISTEN      | 1226/nginx -g daemo
| tcp        | 0      | 0 | 0.0.0.0:22              | 0.0.0.0:*               | LISTEN      | 1138/sshd

### Steps to Reproduce
1. Full production install
2. Validate feeds are working
3. Test any working feed with `testfeeds.py` within the `yeti` dir

#### Expected behavior
Expecting `testfeeds.py` to provide output as per [testing-feeds doc](https://yeti-platform.readthedocs.io/en/latest/extending.html#testing-feeds).

```
$ python testfeeds.py ZeusTrackerConfigs
Running ZeusTrackerConfigs...
ZeusTrackerConfigs: success!
```

#### Actual behavior

Receiving a an issue with what appears to be connections to redis... My guess based on quick review of `scheduling.py` and and `celeryctl.py`.

```
$ python testfeeds.py ZeusTrackerBinaries
Traceback (most recent call last):
  File "testfeeds.py", line 7, in <module>
    Scheduler()
  File "/opt/yeti/core/scheduling.py", line 68, in __init__
    self.load_entries(ScheduleEntry, self.SUBDIRS)
  File "/opt/yeti/core/scheduling.py", line 100, in load_entries
    for sched in ScheduleEntry.objects.all():
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/manager.py", line 37, in __get__
    queryset = queryset_class(owner, owner._get_collection())
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/document.py", line 206, in _get_collection
    cls.ensure_indexes()
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/document.py", line 836, in ensure_indexes
    collection.create_index(fields, background=background, **opts)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1529, in create_index
    self.__create_index(keys, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1417, in __create_index
    with self._socket_for_writes() as sock_info:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 823, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 214, in select_server
    address))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 189, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: connection closed
```

ZeusTrackerBinaries is showing a green status in the UI and I'm seeing data in the app itself. So, everything appears to be working except for the `testfeeds.py`.

<img width="1028" alt="screen shot 2017-05-02 at 5 22 58 pm" src="https://cloud.githubusercontent.com/assets/1697107/25640037/0fa240a8-2f5c-11e7-9111-5a06aa9282bf.png">

<img width="1410" alt="screen shot 2017-05-02 at 5 23 12 pm" src="https://cloud.githubusercontent.com/assets/1697107/25640041/12eaeaa8-2f5c-11e7-92d2-19da30888847.png">

Appreciate any assistance!

**Comment by gaelmuller** [comment]
This is not an error about redis but the error you would have when the script could not connect to MongoDB.

Your netstat output seems to indicate that MongoDB was running though. Could you verify that it is actually running when executing the script ? Are you executing the script on the same production server ?

You could also try restarting MongoDB to see if it changes anything.

**Comment by Tom-Gorup** [comment]
Interesting, I restarted Mongo and all appears to be working again.

```
$ python testfeeds.py ZeusTrackerConfigs
Running ZeusTrackerConfigs...
ZeusTrackerConfigs: success!
```

Happen to know what logs could be reviewed to see where the source of this issue was?

**Comment by tomchop** [comment]
Weird. Looks like mongo closed the connection without warning. Probably the mongo logs in `/var/log`?

**Comment by viszsec** [comment]
Hi guys,

I had issues with relevant feeds with the testfeeds. Same thing occurs if we restart the mongodb. In my case, im using docker.  In yeti webui, the urlhaus works find, but not with the testfeeds.
Appreciate further assistance from all of you, thanks..

yeti@yeti:~/yeti/tests$ python3 testfeeds.py UrlHaus
DEBUG:root:Scheduler started
Traceback (most recent call last):
  File "testfeeds.py", line 14, in <module>
    Scheduler()
  File "/home/yeti/yeti/core/scheduling.py", line 60, in __init__
    self.load_entries()
  File "/home/yeti/yeti/core/scheduling.py", line 80, in load_entries
    self.loaded_entries = get_plugins()
  File "/home/yeti/yeti/core/yeti_plugins.py", line 28, in get_plugins
    for obj in get_plugin_classes():
  File "/home/yeti/yeti/core/yeti_plugins.py", line 17, in get_plugin_classes
    module = importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/yeti/yeti/plugins/analytics/public/macaddress_io.py", line 6, in <module>
    from maclookup import ApiClient, exceptions as maclookup_exceptions
ModuleNotFoundError: No module named 'maclookup'
