### ISSUE TITLE
Unable to add observation file

### ISSUE THREAD

**Issue by DigiAngel** [yeti-platform/yeti#70]
### Description
After submitting a file I get:
~~~
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
~~~

### Environment
| Question         | Answer
|------------------|--------------------
| Git commit       | commit 27ae09f83b0165c36c78297708b4a2e75c9a2dad
| OS version       | Debian stretch
| Browser          | Chrome 57.0.2987.133 (64-bit)

### Steps to Reproduce
1. Submit file - this is a fake rtf file with javascript
2. Get error

#### Expected behavior
Submit successfully

#### Actual behavior
~~~
[2017-05-04 05:34:32,317] ERROR in app: Exception on /observable/ [POST]
Traceback (most recent call last):
  File "/home/jlay/.local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jlay/.local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jlay/.local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jlay/.local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jlay/.local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_classy.py", line 200, in proxy
    response = view(**request.view_args)
  File "/opt/yeti/core/web/helpers.py", line 32, in inner
    return f(*args, **kwargs)
  File "/opt/yeti/core/web/frontend/observables.py", line 85, in index
    o = globals()[request.form['force-type']].get_or_create(value=txt)
  File "/opt/yeti/core/database.py", line 292, in get_or_create
    return obj.save()
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/document.py", line 340, in save
    object_id = collection.save(doc, **write_concern)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 2182, in save
    check_keys, manipulate, write_concern)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 530, in _insert
    check_keys, manipulate, write_concern, op_id, bypass_doc_val)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 512, in _insert_one
    check_keys=check_keys)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 218, in command
    self._raise_connection_failure(error)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 346, in _raise_connection_failure
    raise error
InvalidStringData: strings in documents must be valid UTF-8: '\xd0\xcf\x11<snip>
~~~

**Comment by gaelmuller** [comment]
There is currently no way to do what you are trying to do (upload a file / sample). This feature request is tracked at https://github.com/yeti-platform/yeti/issues/34 following your previous request 😄 

The file upload field on the "Search & Add" page is used to upload a text file containing one observable per line. It is the same as pasting the file contents in the textarea.

**Comment by DigiAngel** [comment]
Oh yea...LoL...sorry for the dup.
