### ISSUE TITLE
TemplateNotFound API Error

### ISSUE THREAD

**Issue by boarterwarding** [yeti-platform/yeti#75]
### Description
I cannot GET any data via the API. This has been tested on a fresh Yeti install as of today. I run into the same error even on different OSes. 

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | commit 827d535061bd760b03dbca8fddaae7962dab7acd
| OS version       | Debian 8.8
| Browser          | FireFox 45.9.0

### Steps to Reproduce
1. git clone the repo
1. cd yeti
1. pip install -r
1. observe stacktrace

#### Expected behavior
Making a HTTP GET request to the API to retrieve information about specific observables, entities etc. 
I can browse the entity manually via the UI without any issues. The entity is a simple test entity which I created.

#### Actual behavior
This is my request:
curl -X GET http://localhost:5000/api/entity/5911ec3fcfd7d70ab0e79e93

This is the HTTP response I'm getting:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

While this is the stack trace from the Yeti application:
[2017-05-09 17:20:39,506] ERROR in app: Exception on /api/entity/5911ec3fcfd7d70ab0e79e93 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_classy.py", line 200, in proxy
    response = view(**request.view_args)
  File "/home/throwaway/gitstuff/yeti/core/web/helpers.py", line 32, in inner
    return f(*args, **kwargs)
  File "/home/throwaway/gitstuff/yeti/core/web/api/crud.py", line 119, in get
    return render(obj, self.template_single)
  File "/usr/local/lib/python2.7/dist-packages/flask_negotiation/__init__.py", line 76, in __call__
    body = renderer.render(data, template, ctx)
  File "/usr/local/lib/python2.7/dist-packages/flask_negotiation/renderers.py", line 69, in render
    return render_template(template, **ctx)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: .html

I've encountered the same issue on a different VM running Yeti.

Let me know if you require more details.

Thanks a lot!

**Comment by tomchop** [comment]
You need to add a header: `Accept: application/json`. FYI, you can also use [httpie](https://httpie.org/) with the `-j` switch.

**Comment by m3047** [comment]
@tomchop I think this issue should be reopened. If an explicit `Accept: application/json` header is not provided, 500 errors are produced with various strange artifacts in the logs.

(Thanks Adam for the sanity check.)

### `Accept: */*` should be accepted

In particular, if you use `python-requests` and you don't explicitly provide the header, `requests` generates `Accept: */*`. I would expect that to work:

```
POST /api/observable/ HTTP/1.1
Host: localhost:5091
Connection: keep-alive
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: python-requests/2.18.4
Content-Length: 79
Content-Type: application/json

{"source": "Manual", "context": {}, "value": "http://foo.bar/zeep", "tags": []}HTTP/1.0 500 INTERNAL SERVER ERROR
Content-Type: text/html
Content-Length: 291
Server: Werkzeug/0.14.1 Python/2.7.12
Date: Wed, 15 May 2019 22:39:19 GMT

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```
