### ISSUE TITLE
Issue getting yeti up and running

### ISSUE THREAD

**Issue by JasonKeirstead** [yeti-platform/yeti#77]
### Description
Hi, I actually hate to raise this as a Github issue but couldn't find any other channel for communication with the team (is there an email or some kind of chat or user forum?)

I am trying to get yeti running on my environment and having numerous problems. Note my platform is OSX.

- When I try to run the UI, after I connect with the browser, it spins for awhile and then this error comes out:

```
[+] Yeti started. Point browser to http://localhost:5000/
[2017-05-12 10:22:08,244] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1610, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1831, in preprocess_request
    rv = func()
  File "/Users/jasonk/git/yeti/core/web/webapp.py", line 53, in frontend_login_required
    if not current_user.is_active and (request.endpoint and request.endpoint != 'frontend.static'):
  File "/usr/local/lib/python2.7/site-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/usr/local/lib/python2.7/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/usr/local/lib/python2.7/site-packages/flask_login/utils.py", line 302, in _get_user
    current_app.login_manager._load_user()
  File "/usr/local/lib/python2.7/site-packages/flask_login/login_manager.py", line 313, in _load_user
    return self._load_from_request(request)
  File "/usr/local/lib/python2.7/site-packages/flask_login/login_manager.py", line 370, in _load_from_request
    user = self.request_callback(request)
  File "/Users/jasonk/git/yeti/core/web/webapp.py", line 44, in api_auth
    return User.objects.get(api_key=request.headers.get('X-Api-Key'))
  File "/usr/local/lib/python2.7/site-packages/mongoengine/queryset/manager.py", line 37, in __get__
    queryset = queryset_class(owner, owner._get_collection())
  File "/usr/local/lib/python2.7/site-packages/mongoengine/document.py", line 206, in _get_collection
    cls.ensure_indexes()
  File "/usr/local/lib/python2.7/site-packages/mongoengine/document.py", line 836, in ensure_indexes
    collection.create_index(fields, background=background, **opts)
  File "/usr/local/lib/python2.7/site-packages/pymongo/collection.py", line 1529, in create_index
    self.__create_index(keys, kwargs)
  File "/usr/local/lib/python2.7/site-packages/pymongo/collection.py", line 1417, in __create_index
    with self._socket_for_writes() as sock_info:
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 823, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/usr/local/lib/python2.7/site-packages/pymongo/topology.py", line 214, in select_server
    address))
  File "/usr/local/lib/python2.7/site-packages/pymongo/topology.py", line 189, in select_servers
    self._error_message(selector))
ServerSelectionTimeoutError: localhost:27017: [Errno 61] Connection refused

```

What server is this trying to connect to on 27017 ?

I get similar issues when I try to run any of the celery services, trying to connect to a weird port.

```
celery -A core.config.celeryctl.celery_app worker --loglevel=ERROR -Q exports -n exports -Ofair -c 2 --purge
[2017-05-12 10:26:14,165: CRITICAL/MainProcess] Unrecoverable error: ConnectionError(u'Error 61 connecting to localhost:6379. Connection refused.',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python2.7/site-packages/celery/bootsteps.py", line 115, in start
    self.on_start()
  File "/usr/local/lib/python2.7/site-packages/celery/apps/worker.py", line 140, in on_start
    self.purge_messages()
  File "/usr/local/lib/python2.7/site-packages/celery/apps/worker.py", line 176, in purge_messages
    count = self.app.control.purge(connection=connection)
  File "/usr/local/lib/python2.7/site-packages/celery/app/control.py", line 178, in purge
    return self.app.amqp.TaskConsumer(conn).purge()
  File "/usr/local/lib/python2.7/site-packages/celery/app/amqp.py", line 302, in TaskConsumer
    **kw
  File "/usr/local/lib/python2.7/site-packages/kombu/messaging.py", line 386, in __init__
    self.revive(self.channel)
  File "/usr/local/lib/python2.7/site-packages/kombu/messaging.py", line 399, in revive
    channel = self.channel = maybe_channel(channel)
  File "/usr/local/lib/python2.7/site-packages/kombu/connection.py", line 973, in maybe_channel
    return channel.default_channel
  File "/usr/local/lib/python2.7/site-packages/kombu/connection.py", line 819, in default_channel
    self.connection
  File "/usr/local/lib/python2.7/site-packages/kombu/connection.py", line 802, in connection
    self._connection = self._establish_connection()
  File "/usr/local/lib/python2.7/site-packages/kombu/connection.py", line 757, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 941, in establish_connection
    self._avail_channels.append(self.create_channel(self))
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 923, in create_channel
    channel = self.Channel(connection)
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 501, in __init__
    self.client.ping()
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 682, in ping
    return self.execute_command('PING')
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 578, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 61 connecting to localhost:6379. Connection refused.
```

**Comment by tomchop** [comment]
No worries for the issue, this is indeed the best way to get in touch with us: issues are public and might get answered by other people should we not see them in time.

More to the point, how did you install Yeti? `localhost:27017` is used for MongoDB, the storage backend. `localhost:6379` is used for communications with Redis, mainly used for scheduling asynchronous tasks such as analytics and feeds. Make sure they're both running and listening on those ports. We should make the error more explicit since you're not the first person to ask this.

**Comment by JasonKeirstead** [comment]
Hrm OK, no problem.

Are there any instructions on how to set up mongo and redis for use with yeti? I don't have any mongo experience and it looks like out of the box it is not set up:

```2017-05-12T10:43:33.554-0300 I CONTROL  [initandlisten] MongoDB starting : pid=98668 port=27017 dbpath=/data/db 64-bit host=jasons-mbp-3.frd.can.ibm.com
2017-05-12T10:43:33.555-0300 I CONTROL  [initandlisten] db version v3.4.4
2017-05-12T10:43:33.555-0300 I CONTROL  [initandlisten] git version: 888390515874a9debd1b6c5d36559ca86b44babd
2017-05-12T10:43:33.555-0300 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017
2017-05-12T10:43:33.555-0300 I CONTROL  [initandlisten] allocator: system
2017-05-12T10:43:33.555-0300 I CONTROL  [initandlisten] modules: none
2017-05-12T10:43:33.555-0300 I CONTROL  [initandlisten] build environment:
2017-05-12T10:43:33.555-0300 I CONTROL  [initandlisten]     distarch: x86_64
2017-05-12T10:43:33.555-0300 I CONTROL  [initandlisten]     target_arch: x86_64
2017-05-12T10:43:33.555-0300 I CONTROL  [initandlisten] options: {}
2017-05-12T10:43:33.557-0300 I STORAGE  [initandlisten] exception in initAndListen: 29 Data directory /data/db not found., terminating
2017-05-12T10:43:33.557-0300 I NETWORK  [initandlisten] shutdown: going to close listening sockets...
2017-05-12T10:43:33.557-0300 I NETWORK  [initandlisten] shutdown: going to flush diaglog...
2017-05-12T10:43:33.557-0300 I CONTROL  [initandlisten] now exiting
2017-05-12T10:43:33.557-0300 I CONTROL  [initandlisten] shutting down with code:100```

**Comment by tomchop** [comment]
What OS are you using? Following the instructions on http://yeti-platform.readthedocs.io/en/latest/installation.html should get you up and running.

**Comment by JasonKeirstead** [comment]
I am on OSX. Those instructions don't say anything about how to setup and run mongo and redis. Are you saying I need an out of box config only for those?

**Comment by gaelmuller** [comment]
You can create a database repository and point to it:

```
$ mkdir ~/mongo_data
$ mongod --dbpath ~/mongo_data
```

You can launch redis with:

```
$ redis-server
```

**Comment by tomchop** [comment]
On OSX, you can install mongo and redis using Homebrew:

```
$ brew install mongodb
$ brew install redis
```

For each, follow the on-screen instructions for launching both services (usually a single command)

**Comment by JasonKeirstead** [comment]
Thanks, I now appear to have it running!

**Comment by tomchop** [comment]
Awesome; closing the issue. Let us know if you run into any other issues.

**Comment by JasonKeirstead** [comment]
Is there any documentation or examples WRT how to create export Templates 
and/or the variables/objects exposed to Jinja in them?

There is a small sample of Jinja code in the page, but it isn't copyable.

-
Jason Keirstead
STSM, Product Architect, Security Intelligence, IBM Security Systems
www.ibm.com/security

Without data, all you are is just another person with an opinion - Unknown
