### ISSUE TITLE
Error model

### ISSUE THREAD

**Issue by sebdraven** [yeti-platform/yeti#783]
[2023-08-18 09:55:12,882: ERROR/ForkPoolWorker-1] Traceback (most recent call last):
  File "/app/plugins/feeds/public/openphish.py", line 40, in analyze
    obs = observable.Observable(value=url, type="url").save()
  File "/app/core/database_arango.py", line 182, in save
    result = self._insert(self.json())
  File "/app/core/database_arango.py", line 153, in _insert
    newdoc = self._get_collection().insert(
  File "/root/.cache/pypoetry/virtualenvs/yeti-9TtSrW0h-py3.10/lib/python3.10/site-packages/arango/collection.py", line 2256, in insert
    document = self._ensure_key_from_id(document)
  File "/root/.cache/pypoetry/virtualenvs/yeti-9TtSrW0h-py3.10/lib/python3.10/site-packages/arango/collection.py", line 199, in _ensure_key_from_id
    doc_id = self._validate_id(body["_id"])
TypeError: string indices must be integers

[2023-08-18 09:55:12,882: ERROR/ForkPoolWorker-1] Error running task OpenPhish: Error analyzing URL: https://sso-login_auth-mail_biglobe_bin-64de87c17fc5d.afghanhoundreview.com/auth-scpf_op-sso-mail_cj-apis/auth.html?resource_url=https://login.sso.biglobe.ne.jp/scpf_op/auth.php?custom_id=77410&session=10715

**Comment by sebdraven** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [openphish.py](https://trello.com/c/LGmiR3Ia/52-openphishpy)
