### ISSUE TITLE
Exception when adding large set of observables

### ISSUE THREAD

**Issue by luckyb56** [yeti-platform/yeti#93]
### Description
Trying to add 1000 observables I see socket exception

### Environment
Ubuntu 16.04

| Question         | Answer
|------------------|--------------------
| Git commit       | commit 5e6a2ad623f465fa370f6d0141e7300674f85b9f
| OS version       | Ubuntu 16.04
| Browser          | Chrome 58.0.3029.110

### Steps to Reproduce
1. Add 1000 or more observables

#### Actual behavior
Exception:
Exception happened during processing of request from ('10.2.0.4', 33872)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

**Comment by tomchop** [comment]
Can you share (here or privately) the list of observables you tried to add? Or at least their type?

**Comment by luckyb56** [comment]
I was running the python webserver earlier. Now I'm using uWSGI. I'll re-run similar test and if any issues will let you know.

**Comment by gaelmuller** [comment]
Closing this since there was no update, do not hesitate to reopen if needed.
